### ISSUE TITLE
When I run "roslaunch cloudproxy client.launch" meet a wrong.

### ISSUE THREAD

**Issue by lianbo2006** [cyberdb/Cloudroid#14]
hello,when I run "roslaunch cloudproxy client.launch" like in Instruction,I meet two mistakes.
The fiest is in the  "proxy.py", there is sort of a  ";" in line 68.

> setting /run_id to c4addb58-3162-11e7-a01a-000c29a919e0
process[rosout-1]: started with pid [10462]
started core service [/rosout]
process[client-2]: started with pid [10465]
Traceback (most recent call last):
  File "/home/lianbo2006-1/catkin_ws/src/cloudproxy/scripts/client", line 6, in <module>
    import cloudproxy.proxy 
  File "/home/lianbo2006-1/catkin_ws/src/cloudproxy/src/cloudproxy/proxy.py", line 68
    else 
        ^
SyntaxError: invalid syntax
[client-2] process has died [pid 10465, exit code 1, cmd /home/lianbo2006-1/catkin_ws/src/cloudproxy/scripts/client http://192.168.204.129:5002 -i 1493944882702 --pub /tf /scan --sub /map --services dynamic_map __name:=client __log:=/home/lianbo2006-1/.ros/log/c4addb58-3162-11e7-a01a-000c29a919e0/client-2.log].
log file: /home/lianbo2006-1/.ros/log/c4addb58-3162-11e7-a01a-000c29a919e0/client-2*.log

When i fix it, there ia another wrong, client will be killed by itself. Please tell me how to fix this problem.

> setting /run_id to 115192fa-315f-11e7-8b46-000c29a919e0
process[rosout-1]: started with pid [10285]
started core service [/rosout]
process[client-2]: started with pid [10289]
No handlers could be found for logger "rosout"
[client-2] process has finished cleanly
log file: /home/lianbo2006-1/.ros/log/115192fa-315f-11e7-8b46-000c29a919e0/client-2*.log

Waiting for your replay!
您好，我在对着手册使用cloudroid遇到了点问题想咨询一下，执行客户端程序时，"proxy.py" 中应该是少了一个分号（上传程序后，从页面下载解压出来放入工作空间的软件包），修改后再执行会遇到客户端自己关闭，返回“No handlers could be found for logger "rosout"”的错误，这个问题不知道是什么原因，有什么办法解决吗？
本来想上传图片的，但是不知道为何上传不上去，看起来可能比较辛苦，麻烦了

**Comment by xiteen** [comment]
Hello, The first thing is a bug. We fixed it this moring:
[https://github.com/cyberdb/Cloudroid/commit/7ed3575975497497e896b1ea4d7af55a43920af2](url)
The second thing may be caused by your ROS system.
[http://forum.erlerobotics.com/t/no-handlers-could-be-found-for-logger-rosout/1866/3](url)
Thanks for your report.

**Comment by lianbo2006** [comment]
/home/lianbo2006/桌面/18200518vm2yoolt32sztf.png

**Comment by lianbo2006** [comment]
I use vmvare to test the system, and i have to test the gmmaping in the vm today, it's run well. However, I can't  run roslaunch cloudproxy client.launch,  it still that "rosout/" wrong.

**Comment by lianbo2006** [comment]
Ok, thaks for provider, I have fixed it. The main problem is not the "rosout/", is docker swarm. Before using "roslaunch", we should start docker swarm which is not mentioned in manual.
